name: Build and Release
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build Package 📦
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone void-packages
        run: git clone --depth=1 https://github.com/void-linux/void-packages.git

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar xz-utils ca-certificates

      - name: Download and install XBPS static binaries
        run: |
          wget https://repo-default.voidlinux.org/static/xbps-static-latest.x86_64-musl.tar.xz
          tar xvf xbps-static-latest.x86_64-musl.tar.xz
          sudo install -Dm755 usr/bin/* /usr/local/bin/

      - name: Bootstrap XBPS-src
        working-directory: void-packages
        run: |
          export XBPS_ARCH=x86_64
          ./xbps-src binary-bootstrap

      - name: Copy template
        run: cp -r srcpkgs/nwg-panel void-packages/srcpkgs/

      - name: Allow restricted packages
        run: echo XBPS_ALLOW_RESTRICTED=yes >> etc/conf
        working-directory: /home/runner/work/nwg-panel-void/nwg-panel-void/void-packages

      - name: Build package
        run: ./xbps-src pkg nwg-panel
        working-directory: /home/runner/work/nwg-panel-void/nwg-panel-void/void-packages

      - name: Upload built packages
        uses: actions/upload-artifact@v4
        with:
          name: nwg-panel-packages
          path: void-packages/hostdir/binpkgs/*.xbps

  release:
    name: Create GitHub Release 🚀
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download built package from artifact
        uses: actions/download-artifact@v4
        with:
          name: nwg-panel-packages

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: "*.xbps"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
